services:
  - type: web
    name: arquitectura-software-upla
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        value: https://xsiqrqctvqxnilqblvaq.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: materiales
      # ── CAMBIOS PARA LA BASE DE DATOS ──
      - key: SUPABASE_DB_HOST
        value: aws-0-ca-central-1.pooler.supabase.com
      - key: SUPABASE_DB_PORT
        value: "6543"
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_DB_USER
        value: postgres.xsiqrqctvqxnilqblvaq
      - key: SUPABASE_DB_PASSWORD
        sync: false
    healthCheckPath: /